# Generated by Django 3.0.6 on 2020-05-12 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_example', models.CharField(max_length=200)),
                ('date_example', models.DateTimeField(verbose_name='Date Example')),
            ],
        ),
        migrations.CreateModel(
            name='Choice_Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text_example', models.CharField(max_length=200)),
                ('votex_example', models.IntegerField(default=0)),
                ('question_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question_Example')),
            ],
        ),
    ]
